# Generated by Django 5.2.6 on 2025-10-02 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='user_online',
            field=models.ManyToManyField(blank=True, related_name='onine_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
